package org.apache.xmlbeans.impl.tool;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.net.URI;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.apache.commons.codec.language.bm.Rule;
import org.apache.commons.collections4.CollectionUtils;
import org.apache.logging.log4j.util.ProcessIdUtil;
import org.apache.xmlbeans.ResourceLoader;
import org.apache.xmlbeans.SchemaType;
import org.apache.xmlbeans.SchemaTypeLoader;
import org.apache.xmlbeans.SchemaTypeSystem;
import org.apache.xmlbeans.SimpleValue;
import org.apache.xmlbeans.XmlBeans;
import org.apache.xmlbeans.XmlError;
import org.apache.xmlbeans.XmlErrorCodes;
import org.apache.xmlbeans.XmlException;
import org.apache.xmlbeans.XmlObject;
import org.apache.xmlbeans.XmlOptions;
import org.apache.xmlbeans.impl.common.XmlErrorWatcher;
import org.apache.xmlbeans.impl.config.BindingConfigImpl;
import org.apache.xmlbeans.impl.schema.SchemaTypeLoaderImpl;
import org.apache.xmlbeans.impl.schema.SchemaTypeSystemCompiler;
import org.apache.xmlbeans.impl.schema.StscState;
import org.apache.xmlbeans.impl.tool.Extension;
import org.apache.xmlbeans.impl.xb.substwsdl.DefinitionsDocument;
import org.apache.xmlbeans.impl.xb.xmlconfig.ConfigDocument;
import org.apache.xmlbeans.impl.xb.xmlconfig.Extensionconfig;
import org.apache.xmlbeans.impl.xb.xsdschema.SchemaDocument;
import org.xml.sax.EntityResolver;

/* loaded from: classes11.dex */
public class SchemaCompiler {
    static final /* synthetic */ boolean $assertionsDisabled = false;
    private static final String COMPATIBILITY_CONFIG_URI = "http://www.bea.com/2002/09/xbean/config";
    private static final String CONFIG_URI = "http://xml.apache.org/xmlbeans/2004/02/xbean/config";
    private static final Map<String, String> MAP_COMPATIBILITY_CONFIG_URIS = Collections.singletonMap(COMPATIBILITY_CONFIG_URI, CONFIG_URI);

    public static void printUsage() {
        System.out.println("Compiles a schema into XML Bean classes and metadata.");
        System.out.println("Usage: scomp [opts] [dirs]* [schema.xsd]* [service.wsdl]* [config.xsdconfig]*");
        System.out.println("Options include:");
        System.out.println("    -cp [a;b;c] - classpath");
        System.out.println("    -d [dir] - target binary directory for .class and .xsb files");
        System.out.println("    -src [dir] - target directory for generated .java files");
        System.out.println("    -srconly - do not compile .java files or jar the output.");
        System.out.println("    -out [xmltypes.jar] - the name of the output jar");
        System.out.println("    -name - the name of the schema type - defaults to autogenerated name");
        System.out.println("    -dl - permit network downloads for imports and includes (default is off)");
        System.out.println("    -noupa - do not enforce the unique particle attribution rule");
        System.out.println("    -nopvr - do not enforce the particle valid (restriction) rule");
        System.out.println("    -noann - ignore annotations");
        System.out.println("    -novdoc - do not validate contents of <documentation>");
        System.out.println("    -noext - ignore all extension (Pre/Post and Interface) found in .xsdconfig files");
        System.out.println("    -compiler - path to external java compiler");
        System.out.println("    -ms - initial memory for external java compiler (default '8m')");
        System.out.println("    -mx - maximum memory for external java compiler (default '256m')");
        System.out.println("    -debug - compile with debug symbols");
        System.out.println("    -quiet - print fewer informational messages");
        System.out.println("    -verbose - print more informational messages");
        System.out.println("    -version - prints version information");
        System.out.println("    -license - prints license information");
        System.out.println("    -allowmdef \"[ns] [ns] [ns]\" - ignores multiple defs in given namespaces (use ##local for no-namespace)");
        System.out.println("    -catalog [file] -  catalog file for org.apache.xml.resolver.tools.CatalogResolver. (Note: needs resolver.jar from http://xml.apache.org/commons/components/resolver/index.html)");
        System.out.println("    -partialMethods [list] -  comma separated list of bean methods to be generated. Use \"-\" to negate and \"ALL\" for all.");
        System.out.println("                              processed left-to-right, e.g. \"ALL,-GET_LIST\" exclude java.util.List getters - see XmlOptions.BeanMethod");
        System.out.println("    -repackage - repackage specification, e.g. \"org.apache.xmlbeans.metadata:mypackage.metadata\" to change the metadata directory");
        System.out.println("    -copyann - copy schema annotations to javadoc (default false) - don't activate on untrusted schema sources!");
        System.out.println("    -sourcecodeencoding [encodingName] - Generate Java source code with the specified encoding (ISO-8859-1 is the legacy default)");
        System.out.println();
    }

    /* JADX WARN: Can't wrap try/catch for region: R(64:31|(1:33)(1:213)|34|(1:36)(1:212)|(1:38)(1:211)|(1:40)|41|(58:199|200|201|202|203|204|45|(1:47)(1:198)|48|(1:50)(1:197)|51|(1:53)(1:196)|54|(1:56)(1:195)|57|(1:59)(1:194)|60|(1:62)(1:193)|63|(1:65)(1:192)|66|(1:68)(1:191)|69|(1:71)(1:190)|72|(1:74)(1:189)|75|(14:160|161|162|163|164|165|166|167|168|169|170|171|172|173)(1:77)|78|(4:82|(4:85|(2:87|88)(2:90|91)|89|83)|92|93)|94|(1:96)(1:159)|97|(1:99)(1:158)|(1:157)(1:103)|104|(21:151|152|153|109|(1:150)(1:113)|(1:115)|(1:117)(1:149)|(1:119)(1:148)|120|(4:122|(1:124)|125|126)(1:147)|127|(1:146)(1:130)|131|(1:133)(1:145)|134|(1:136)(1:144)|137|(1:139)|(1:141)|142|143)(1:107)|108|109|(0)|150|(0)|(0)(0)|(0)(0)|120|(0)(0)|127|(0)|146|131|(0)(0)|134|(0)(0)|137|(0)|(0)|142|143)(1:43)|44|45|(0)(0)|48|(0)(0)|51|(0)(0)|54|(0)(0)|57|(0)(0)|60|(0)(0)|63|(0)(0)|66|(0)(0)|69|(0)(0)|72|(0)(0)|75|(0)(0)|78|(5:80|82|(1:83)|92|93)|94|(0)(0)|97|(0)(0)|(0)|157|104|(0)|151|152|153|109|(0)|150|(0)|(0)(0)|(0)(0)|120|(0)(0)|127|(0)|146|131|(0)(0)|134|(0)(0)|137|(0)|(0)|142|143) */
    /* JADX WARN: Code restructure failed: missing block: B:155:0x038d, code lost:
    
        r0 = move-exception;
     */
    /* JADX WARN: Code restructure failed: missing block: B:156:0x038e, code lost:
    
        r34 = r9;
        r35 = r8;
        java.lang.System.err.println("Error creating temp dir " + r0);
        java.lang.System.exit(r26);
     */
    /* JADX WARN: Multi-variable type inference failed */
    /* JADX WARN: Removed duplicated region for block: B:101:0x0368 A[ADDED_TO_REGION] */
    /* JADX WARN: Removed duplicated region for block: B:106:0x0376 A[ADDED_TO_REGION] */
    /* JADX WARN: Removed duplicated region for block: B:111:0x03b4 A[ADDED_TO_REGION] */
    /* JADX WARN: Removed duplicated region for block: B:115:0x03bf  */
    /* JADX WARN: Removed duplicated region for block: B:117:0x03c7  */
    /* JADX WARN: Removed duplicated region for block: B:119:0x03d2  */
    /* JADX WARN: Removed duplicated region for block: B:122:0x03e5  */
    /* JADX WARN: Removed duplicated region for block: B:129:0x043a A[ADDED_TO_REGION] */
    /* JADX WARN: Removed duplicated region for block: B:133:0x048d  */
    /* JADX WARN: Removed duplicated region for block: B:136:0x04a4  */
    /* JADX WARN: Removed duplicated region for block: B:139:0x0569  */
    /* JADX WARN: Removed duplicated region for block: B:141:0x056e  */
    /* JADX WARN: Removed duplicated region for block: B:144:0x04a6  */
    /* JADX WARN: Removed duplicated region for block: B:145:0x049c  */
    /* JADX WARN: Removed duplicated region for block: B:147:0x0422  */
    /* JADX WARN: Removed duplicated region for block: B:148:0x03d9  */
    /* JADX WARN: Removed duplicated region for block: B:149:0x03ce  */
    /* JADX WARN: Removed duplicated region for block: B:158:0x0364  */
    /* JADX WARN: Removed duplicated region for block: B:159:0x0350  */
    /* JADX WARN: Removed duplicated region for block: B:160:0x0268 A[EXC_TOP_SPLITTER, SYNTHETIC] */
    /* JADX WARN: Removed duplicated region for block: B:189:0x0247  */
    /* JADX WARN: Removed duplicated region for block: B:190:0x022d  */
    /* JADX WARN: Removed duplicated region for block: B:191:0x0220  */
    /* JADX WARN: Removed duplicated region for block: B:192:0x0211  */
    /* JADX WARN: Removed duplicated region for block: B:193:0x0202  */
    /* JADX WARN: Removed duplicated region for block: B:194:0x01f3  */
    /* JADX WARN: Removed duplicated region for block: B:195:0x01e4  */
    /* JADX WARN: Removed duplicated region for block: B:196:0x01d7  */
    /* JADX WARN: Removed duplicated region for block: B:197:0x01cc  */
    /* JADX WARN: Removed duplicated region for block: B:198:0x01c1  */
    /* JADX WARN: Removed duplicated region for block: B:47:0x01be  */
    /* JADX WARN: Removed duplicated region for block: B:50:0x01c9  */
    /* JADX WARN: Removed duplicated region for block: B:53:0x01d4  */
    /* JADX WARN: Removed duplicated region for block: B:56:0x01e1  */
    /* JADX WARN: Removed duplicated region for block: B:59:0x01f0  */
    /* JADX WARN: Removed duplicated region for block: B:62:0x01ff  */
    /* JADX WARN: Removed duplicated region for block: B:65:0x020e  */
    /* JADX WARN: Removed duplicated region for block: B:68:0x021d  */
    /* JADX WARN: Removed duplicated region for block: B:71:0x022a  */
    /* JADX WARN: Removed duplicated region for block: B:74:0x0240  */
    /* JADX WARN: Removed duplicated region for block: B:77:0x02d3  */
    /* JADX WARN: Removed duplicated region for block: B:80:0x02e1  */
    /* JADX WARN: Removed duplicated region for block: B:85:0x0301  */
    /* JADX WARN: Removed duplicated region for block: B:96:0x0349  */
    /* JADX WARN: Removed duplicated region for block: B:99:0x035c  */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public static void main(java.lang.String[] r51) {
        /*
            Method dump skipped, instructions count: 1410
            To view this dump add '--comments-level debug' option
        */
        throw new UnsupportedOperationException("Method not decompiled: org.apache.xmlbeans.impl.tool.SchemaCompiler.main(java.lang.String[]):void");
    }

    private static SchemaTypeSystem loadTypeSystem(String name, File[] xsdFiles, File[] wsdlFiles, URL[] urlFiles, File[] configFiles, File[] javaFiles, ResourceLoader cpResourceLoader, boolean download, boolean noUpa, boolean noPvr, boolean noAnn, boolean noVDoc, boolean noExt, String sourceCodeEncoding, Set<String> mdefNamespaces, File baseDir, Map<String, String> sourcesToCopyMap, Collection<XmlError> outerErrorListener, File schemasDir, EntityResolver entResolver, File[] classpath) {
        int i;
        File xsdFile;
        int i2;
        String str;
        int i3;
        int i4;
        File wsdlFile;
        int i5;
        XmlOptions options;
        File[] fileArr = configFiles;
        XmlErrorWatcher errorListener = new XmlErrorWatcher(outerErrorListener);
        StscState state = StscState.start();
        try {
            state.setErrorListener(errorListener);
            SchemaTypeLoader loader = XmlBeans.typeLoaderForClassLoader(SchemaDocument.class.getClassLoader());
            ArrayList<SchemaDocument.Schema> scontentlist = new ArrayList<>();
            if (xsdFiles != null) {
                try {
                    int length = xsdFiles.length;
                    int i6 = 0;
                    while (i6 < length) {
                        File xsdFile2 = xsdFiles[i6];
                        try {
                            XmlOptions options2 = new XmlOptions();
                            options2.setLoadLineNumbers();
                            options2.setLoadMessageDigest();
                            options2.setEntityResolver(entResolver);
                            i = i6;
                            xsdFile = xsdFile2;
                            i2 = length;
                            try {
                                XmlObject schemadoc = loader.parse(xsdFile, (SchemaType) null, options2);
                                if (schemadoc instanceof SchemaDocument) {
                                    addSchema(xsdFile.toString(), (SchemaDocument) schemadoc, errorListener, noVDoc, scontentlist);
                                } else {
                                    StscState.addError(errorListener, XmlErrorCodes.INVALID_DOCUMENT_TYPE, new Object[]{xsdFile, "schema"}, schemadoc);
                                }
                            } catch (XmlException e) {
                                e = e;
                                errorListener.add(e.getError());
                                i6 = i + 1;
                                length = i2;
                            } catch (Exception e2) {
                                e = e2;
                                StscState.addError(errorListener, XmlErrorCodes.CANNOT_LOAD_FILE, new Object[]{"xsd", xsdFile, e.getMessage()}, xsdFile);
                                i6 = i + 1;
                                length = i2;
                            }
                        } catch (XmlException e3) {
                            e = e3;
                            i = i6;
                            i2 = length;
                        } catch (Exception e4) {
                            e = e4;
                            i = i6;
                            xsdFile = xsdFile2;
                            i2 = length;
                        }
                        i6 = i + 1;
                        length = i2;
                    }
                } catch (Throwable th) {
                    th = th;
                    StscState.end();
                    throw th;
                }
            }
            String str2 = "http://www.apache.org/internal/xmlbeans/wsdlsubst";
            if (wsdlFiles != null) {
                int length2 = wsdlFiles.length;
                int i7 = 0;
                while (i7 < length2) {
                    File wsdlFile2 = wsdlFiles[i7];
                    try {
                        options = new XmlOptions();
                        options.setLoadLineNumbers();
                        i4 = i7;
                    } catch (XmlException e5) {
                        e = e5;
                        i4 = i7;
                    } catch (Exception e6) {
                        e = e6;
                        i4 = i7;
                    }
                    try {
                        options.setLoadSubstituteNamespaces(Collections.singletonMap("http://schemas.xmlsoap.org/wsdl/", "http://www.apache.org/internal/xmlbeans/wsdlsubst"));
                        options.setEntityResolver(entResolver);
                        wsdlFile = wsdlFile2;
                        i5 = length2;
                        try {
                            XmlObject wsdldoc = loader.parse(wsdlFile, (SchemaType) null, options);
                            if (wsdldoc instanceof DefinitionsDocument) {
                                addWsdlSchemas(wsdlFile.toString(), (DefinitionsDocument) wsdldoc, errorListener, noVDoc, scontentlist);
                            } else {
                                StscState.addError(errorListener, XmlErrorCodes.INVALID_DOCUMENT_TYPE, new Object[]{wsdlFile, "wsdl"}, wsdldoc);
                            }
                        } catch (XmlException e7) {
                            e = e7;
                            errorListener.add(e.getError());
                            i7 = i4 + 1;
                            length2 = i5;
                        } catch (Exception e8) {
                            e = e8;
                            StscState.addError(errorListener, XmlErrorCodes.CANNOT_LOAD_FILE, new Object[]{"wsdl", wsdlFile, e.getMessage()}, wsdlFile);
                            i7 = i4 + 1;
                            length2 = i5;
                        }
                    } catch (XmlException e9) {
                        e = e9;
                        i5 = length2;
                        errorListener.add(e.getError());
                        i7 = i4 + 1;
                        length2 = i5;
                    } catch (Exception e10) {
                        e = e10;
                        wsdlFile = wsdlFile2;
                        i5 = length2;
                        StscState.addError(errorListener, XmlErrorCodes.CANNOT_LOAD_FILE, new Object[]{"wsdl", wsdlFile, e.getMessage()}, wsdlFile);
                        i7 = i4 + 1;
                        length2 = i5;
                    }
                    i7 = i4 + 1;
                    length2 = i5;
                }
            }
            if (urlFiles != null) {
                int length3 = urlFiles.length;
                int i8 = 0;
                while (i8 < length3) {
                    URL urlFile = urlFiles[i8];
                    try {
                        XmlOptions options3 = new XmlOptions();
                        options3.setLoadLineNumbers();
                        i3 = length3;
                        try {
                            options3.setLoadSubstituteNamespaces(Collections.singletonMap("http://schemas.xmlsoap.org/wsdl/", str2));
                            options3.setEntityResolver(entResolver);
                            XmlObject urldoc = loader.parse(urlFile, (SchemaType) null, options3);
                            if (urldoc instanceof DefinitionsDocument) {
                                str = str2;
                                try {
                                    addWsdlSchemas(urlFile.toString(), (DefinitionsDocument) urldoc, errorListener, noVDoc, scontentlist);
                                } catch (XmlException e11) {
                                    e = e11;
                                    errorListener.add(e.getError());
                                    i8++;
                                    length3 = i3;
                                    str2 = str;
                                } catch (Exception e12) {
                                    e = e12;
                                    StscState.addError(errorListener, XmlErrorCodes.CANNOT_LOAD_FILE, new Object[]{"url", urlFile, e.getMessage()}, urlFile);
                                    i8++;
                                    length3 = i3;
                                    str2 = str;
                                }
                            } else {
                                str = str2;
                                if (urldoc instanceof SchemaDocument) {
                                    addSchema(urlFile.toString(), (SchemaDocument) urldoc, errorListener, noVDoc, scontentlist);
                                } else {
                                    StscState.addError(errorListener, XmlErrorCodes.INVALID_DOCUMENT_TYPE, new Object[]{urlFile, "wsdl or schema"}, urldoc);
                                }
                            }
                        } catch (XmlException e13) {
                            e = e13;
                            str = str2;
                        } catch (Exception e14) {
                            e = e14;
                            str = str2;
                        }
                    } catch (XmlException e15) {
                        e = e15;
                        str = str2;
                        i3 = length3;
                    } catch (Exception e16) {
                        e = e16;
                        str = str2;
                        i3 = length3;
                    }
                    i8++;
                    length3 = i3;
                    str2 = str;
                }
            }
            SchemaDocument.Schema[] sdocs = (SchemaDocument.Schema[]) scontentlist.toArray(new SchemaDocument.Schema[0]);
            ArrayList<ConfigDocument.Config> cdoclist = new ArrayList<>();
            if (fileArr != null) {
                if (noExt) {
                    System.out.println("Pre/Post and Interface extensions will be ignored.");
                }
                int length4 = fileArr.length;
                int i9 = 0;
                while (i9 < length4) {
                    File configFile = fileArr[i9];
                    try {
                        try {
                            XmlOptions options4 = new XmlOptions();
                            options4.setLoadLineNumbers();
                            options4.setEntityResolver(entResolver);
                            options4.setLoadSubstituteNamespaces(MAP_COMPATIBILITY_CONFIG_URIS);
                            XmlObject configdoc = loader.parse(configFile, (SchemaType) null, options4);
                            if (configdoc instanceof ConfigDocument) {
                                StscState.addInfo(errorListener, "Loading config file " + configFile);
                                if (configdoc.validate(new XmlOptions().setErrorListener(errorListener))) {
                                    ConfigDocument.Config config = ((ConfigDocument) configdoc).getConfig();
                                    cdoclist.add(config);
                                    if (noExt) {
                                        config.setExtensionArray(new Extensionconfig[0]);
                                    }
                                }
                            } else {
                                StscState.addError(errorListener, XmlErrorCodes.INVALID_DOCUMENT_TYPE, new Object[]{configFile, "xsd config"}, configdoc);
                            }
                        } catch (Exception e17) {
                            StscState.addError(errorListener, XmlErrorCodes.CANNOT_LOAD_FILE, new Object[]{"xsd config", configFile, e17.getMessage()}, configFile);
                        }
                    } catch (XmlException e18) {
                        errorListener.add(e18.getError());
                    }
                    i9++;
                    fileArr = configFiles;
                }
            }
            ConfigDocument.Config[] cdocs = (ConfigDocument.Config[]) cdoclist.toArray(new ConfigDocument.Config[0]);
            SchemaTypeLoader linkTo = SchemaTypeLoaderImpl.build(null, cpResourceLoader, null);
            URI baseURI = baseDir != null ? baseDir.toURI() : null;
            XmlOptions opts = new XmlOptions();
            if (download) {
                opts.setCompileDownloadUrls();
            }
            if (noUpa) {
                opts.setCompileNoUpaRule();
            }
            if (noPvr) {
                opts.setCompileNoPvrRule();
            }
            if (noAnn) {
                opts.setCompileNoAnnotations();
            }
            if (sourceCodeEncoding != null) {
                try {
                    opts.setCharacterEncoding(sourceCodeEncoding);
                } catch (Throwable th2) {
                    th = th2;
                    StscState.end();
                    throw th;
                }
            }
            if (mdefNamespaces != null) {
                try {
                    opts.setCompileMdefNamespaces(mdefNamespaces);
                } catch (Throwable th3) {
                    th = th3;
                    StscState.end();
                    throw th;
                }
            }
            opts.setCompileNoValidation();
            opts.setEntityResolver(entResolver);
            SchemaTypeSystemCompiler.Parameters params = new SchemaTypeSystemCompiler.Parameters();
            try {
                params.setName(name);
                params.setSchemas(sdocs);
                try {
                    params.setConfig(BindingConfigImpl.forConfigDocuments(cdocs, javaFiles, classpath));
                    params.setLinkTo(linkTo);
                    params.setOptions(opts);
                    params.setErrorListener(errorListener);
                    params.setJavaize(true);
                    params.setBaseURI(baseURI);
                    try {
                        params.setSourcesToCopyMap(sourcesToCopyMap);
                        try {
                            params.setSchemasDir(schemasDir);
                            SchemaTypeSystem compile = SchemaTypeSystemCompiler.compile(params);
                            StscState.end();
                            return compile;
                        } catch (Throwable th4) {
                            th = th4;
                            StscState.end();
                            throw th;
                        }
                    } catch (Throwable th5) {
                        th = th5;
                        StscState.end();
                        throw th;
                    }
                } catch (Throwable th6) {
                    th = th6;
                }
            } catch (Throwable th7) {
                th = th7;
                StscState.end();
                throw th;
            }
        } catch (Throwable th8) {
            th = th8;
        }
    }

    private static void addSchema(String name, SchemaDocument schemadoc, XmlErrorWatcher errorListener, boolean noVDoc, List<SchemaDocument.Schema> scontentlist) {
        StscState.addInfo(errorListener, "Loading schema file " + name);
        XmlOptions opts = new XmlOptions().setErrorListener(errorListener);
        if (noVDoc) {
            opts.setValidateTreatLaxAsSkip();
        }
        if (schemadoc.validate(opts)) {
            scontentlist.add(schemadoc.getSchema());
        }
    }

    private static void addWsdlSchemas(String name, DefinitionsDocument wsdldoc, XmlErrorWatcher errorListener, boolean noVDoc, List<SchemaDocument.Schema> scontentlist) {
        int i = 60;
        if (wsdlContainsEncoded(wsdldoc)) {
            StscState.addWarning(errorListener, "The WSDL " + name + " uses SOAP encoding. SOAP encoding is not compatible with literal XML Schema.", 60, wsdldoc);
        }
        StscState.addInfo(errorListener, "Loading wsdl file " + name);
        XmlOptions opts = new XmlOptions().setErrorListener(errorListener);
        if (noVDoc) {
            opts.setValidateTreatLaxAsSkip();
        }
        XmlObject[] types = wsdldoc.getDefinitions().getTypesArray();
        int count = 0;
        int length = types.length;
        int i2 = 0;
        while (i2 < length) {
            XmlObject type = types[i2];
            XmlObject[] schemas = type.selectPath("declare namespace xs=\"http://www.w3.org/2001/XMLSchema\" xs:schema");
            if (schemas.length == 0) {
                StscState.addWarning(errorListener, "The WSDL " + name + " did not have any schema documents in namespace 'http://www.w3.org/2001/XMLSchema'", i, wsdldoc);
            } else {
                for (XmlObject schema : schemas) {
                    if (schema.validate(opts)) {
                        count++;
                        scontentlist.add((SchemaDocument.Schema) schema);
                    }
                }
            }
            i2++;
            i = 60;
        }
        StscState.addInfo(errorListener, "Processing " + count + " schema(s) in " + name);
    }

    /* JADX WARN: Removed duplicated region for block: B:70:0x03ac  */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public static boolean compile(org.apache.xmlbeans.impl.tool.Parameters r58) {
        /*
            Method dump skipped, instructions count: 1008
            To view this dump add '--comments-level debug' option
        */
        throw new UnsupportedOperationException("Method not decompiled: org.apache.xmlbeans.impl.tool.SchemaCompiler.compile(org.apache.xmlbeans.impl.tool.Parameters):boolean");
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public static Set<XmlOptions.BeanMethod> parsePartialMethods(String str) {
        HashSet hashSet = new HashSet();
        if (str != null) {
            for (String str2 : str.split(CollectionUtils.COMMA)) {
                if (Rule.ALL.equals(str2)) {
                    hashSet.addAll(Arrays.asList(XmlOptions.BeanMethod.values()));
                } else {
                    boolean startsWith = str2.startsWith(ProcessIdUtil.DEFAULT_PROCESSID);
                    XmlOptions.BeanMethod valueOf = XmlOptions.BeanMethod.valueOf(str2.substring(startsWith ? 1 : 0));
                    if (startsWith) {
                        hashSet.remove(valueOf);
                    } else {
                        hashSet.add(valueOf);
                    }
                }
            }
        }
        if (hashSet.isEmpty()) {
            return null;
        }
        return hashSet;
    }

    private static void runExtensions(List<Extension> extensions, SchemaTypeSystem system, File classesDir) {
        String classesDirName;
        if (extensions != null && !extensions.isEmpty()) {
            try {
                classesDirName = classesDir.getCanonicalPath();
            } catch (IOException e) {
                System.out.println("WARNING: Unable to get the path for schema jar file");
                classesDirName = classesDir.getAbsolutePath();
            }
            for (Extension extension : extensions) {
                try {
                    SchemaCompilerExtension sce = (SchemaCompilerExtension) extension.getClassName().getDeclaredConstructor(new Class[0]).newInstance(new Object[0]);
                    System.out.println("Running Extension: " + sce.getExtensionName());
                    Map<String, String> extensionParms = new HashMap<>();
                    for (Extension.Param p : extension.getParams()) {
                        extensionParms.put(p.getName(), p.getValue());
                    }
                    extensionParms.put("classesDir", classesDirName);
                    sce.schemaCompilerExtension(system, extensionParms);
                } catch (IllegalAccessException e2) {
                    System.out.println("ILLEGAL ACCESS Exception when attempting to instantiate schema compiler extension: " + extension.getClassName().getName());
                    System.out.println("EXTENSION Class was not run");
                    return;
                } catch (InstantiationException e3) {
                    System.out.println("UNABLE to instantiate schema compiler extension:" + extension.getClassName().getName());
                    System.out.println("EXTENSION Class was not run");
                    return;
                } catch (NoSuchMethodException e4) {
                    System.out.println("UNABLE to instantiate schema compiler extension:" + extension.getClassName().getName());
                    System.out.println("EXTENSION Class was not run");
                    return;
                } catch (InvocationTargetException e5) {
                    System.out.println("ILLEGAL ACCESS Exception when attempting to instantiate schema compiler extension: " + extension.getClassName().getName());
                    System.out.println("EXTENSION Class was not run");
                    return;
                }
            }
        }
    }

    private static boolean wsdlContainsEncoded(XmlObject wsdldoc) {
        XmlObject[] useAttrs = wsdldoc.selectPath("declare namespace soap='http://schemas.xmlsoap.org/wsdl/soap/' .//soap:body/@use|.//soap:header/@use|.//soap:fault/@use");
        for (XmlObject useAttr : useAttrs) {
            if ("encoded".equals(((SimpleValue) useAttr).getStringValue())) {
                return true;
            }
        }
        return false;
    }
}
